// Package promptfile keeps the standing instructions AO hands an agent in a
// private file, so they never ride on the agent's command line.
//
// A command line is not private and it is not inert. Every process on the
// machine can read it (`ps`), and `pkill -f <word>` matches against it, so a
// system prompt passed as `--append-system-prompt "<text>"` makes every agent
// whose instructions contain a word killable by anyone who pattern-kills that
// word. On 2026-09-22 a worker cleaning up a stuck build ran
// `pkill -f 'xcodebuild test'`, and every iOS agent on the machine died with it,
// because the simulator guidance in their system prompt mentions that command.
// The agent is handed a path instead; the text lives here.
//
// Files live under <dataDir>/prompts/<session id>/, one directory per session
// so a session's files are removed together when it ends (see Remove), with the
// directory 0700 and every file 0600: the instructions are the operator's, not
// the machine's.
package promptfile

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/aoagents/agent-orchestrator/backend/internal/domain"
	"github.com/aoagents/agent-orchestrator/backend/internal/fsatomic"
)

// The file names a session's directory holds. A worker's reviewer pane lives
// and dies with the worker, so its instructions are kept beside the worker's own
// and are removed with them.
const (
	SystemPrompt         = "system-prompt.md"
	ReviewerSystemPrompt = "reviewer-system-prompt.md"
)

// dirName is the directory under the data dir that holds every session's files.
const dirName = "prompts"

// Root returns the directory that holds every session's prompt files.
func Root(dataDir string) string {
	return filepath.Join(dataDir, dirName)
}

// Dir returns the directory that holds one session's prompt files.
func Dir(dataDir string, owner domain.SessionID) string {
	return filepath.Join(Root(dataDir), string(owner))
}

// Write stores text as the session's file called name and returns its path.
// The replacement is atomic, so an agent starting while a relaunch rewrites
// the file reads either the old instructions or the new ones, never half of
// each. Empty text writes nothing and returns an empty path: there is nothing
// to hand the agent.
func Write(dataDir string, owner domain.SessionID, name, text string) (string, error) {
	if text == "" {
		return "", nil
	}
	if dataDir == "" {
		return "", errors.New("promptfile: data dir is required")
	}
	if err := validOwner(owner); err != nil {
		return "", err
	}
	if name == "" || filepath.Base(name) != name {
		return "", fmt.Errorf("promptfile: invalid file name %q", name)
	}
	dir := Dir(dataDir, owner)
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return "", fmt.Errorf("promptfile: prepare %s: %w", dir, err)
	}
	// MkdirAll leaves an existing directory's mode alone; tighten it so a
	// directory created by an older build is private too.
	if err := os.Chmod(dir, 0o700); err != nil { //nolint:gosec // G302: a directory needs its x bit; 0700 is owner-only
		return "", fmt.Errorf("promptfile: prepare %s: %w", dir, err)
	}
	path := filepath.Join(dir, name)
	if err := fsatomic.WriteFile(path, []byte(text), 0o600); err != nil {
		return "", fmt.Errorf("promptfile: write %s: %w", path, err)
	}
	return path, nil
}

// Remove deletes every prompt file the session owns. A session that never had
// any is not an error.
func Remove(dataDir string, owner domain.SessionID) error {
	if dataDir == "" {
		return nil
	}
	if err := validOwner(owner); err != nil {
		return err
	}
	if err := os.RemoveAll(Dir(dataDir, owner)); err != nil {
		return fmt.Errorf("promptfile: remove %s: %w", owner, err)
	}
	return nil
}

// Owners lists the sessions that have prompt files on disk, for the boot sweep
// that removes the files of sessions which ended while the daemon was down.
func Owners(dataDir string) ([]domain.SessionID, error) {
	if dataDir == "" {
		return nil, nil
	}
	entries, err := os.ReadDir(Root(dataDir))
	if errors.Is(err, fs.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("promptfile: list: %w", err)
	}
	owners := make([]domain.SessionID, 0, len(entries))
	for _, e := range entries {
		if e.IsDir() {
			owners = append(owners, domain.SessionID(e.Name()))
		}
	}
	return owners, nil
}

// validOwner refuses an id that would escape the prompts directory. Session ids
// are generated by AO and never contain a separator; this is the guard that
// keeps a Remove from ever reaching outside it.
func validOwner(owner domain.SessionID) error {
	s := string(owner)
	if s == "" || s == "." || s == ".." || strings.ContainsAny(s, `/\`) {
		return fmt.Errorf("promptfile: invalid session id %q", s)
	}
	return nil
}
